services:
  - type: web
    name: dhara-rakshak-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python backend/manage.py collectstatic --noinput
      python backend/manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_NGZ81zmXtSbk@ep-raspy-feather-a12909q5-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11.9
