# Generated by Django 5.2.3 on 2025-07-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mandal', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('document_number', models.CharField(max_length=50)),
                ('survey_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='land_photos/')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
